directory: /run/user/1000/gvfs/smb-share:server=192.168.103.7,share=media/Music/Lidarr
library: ~/Music/beets.db
import:
  copy: no
  write: no

plugins:
- playlist

playlist:
  auto: no
  relative_to: /run/user/1000/gvfs/smb-share:server=192.168.103.7,share=media/Music/Playlists
  playlist_dir: /run/user/1000/gvfs/smb-share:server=192.168.103.7,share=media/Music/Playlists
  forward_slash: no
